name: Build "turnip"

on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 1,15 * *"

jobs:
  start_building_turnip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare timezone 
      run: |
            echo "BUILD_TIME=$(TZ=Asia/Jakarta date "+%d%m%Y")" >> $GITHUB_ENV
            sudo rm /etc/localtime
            sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
        
    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt build-dep mesa -y

    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          turnip_workdir/ninja_log
          turnip_workdir/mesa-main/build-android-aarch64/meson-logs/meson-log.txt

    - name: Release "turnip"
      uses: softprops/action-gh-release@v1
      with:
        body: Turnip magisk module and driver package for adrenotools
        tag_name: github_run
        name: Weekly Release ${{ env.BUILD_TIME }}
        files: |
           turnip_workdir/turnip.zip
           turnip_workdir/turnip_adrenotools.zip
